services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_pass
      POSTGRES_DB: stats_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats_user -d stats_db"]
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=stats_user
      - SPRING_DATASOURCE_PASSWORD=stats_pass
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_USER: ewm_user
      POSTGRES_PASSWORD: ewm_pass
      POSTGRES_DB: ewm_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm_user -d ewm_db"]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=ewm_user
      - SPRING_DATASOURCE_PASSWORD=ewm_pass
    depends_on:
      ewm-db:
        condition: service_healthy
    ports:
      - "8080:8080"